# CMake generated Testfile for 
# Source directory: /home/riccardochiaretti/alba_v2_hmi/src/hmi_node
# Build directory: /home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(copyright "/usr/bin/python3" "-u" "/home/riccardochiaretti/ros2_eloquent/install/ament_cmake_test/share/ament_cmake_test/cmake/run_test.py" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/copyright.xunit.xml" "--package-name" "hmi_node" "--output-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/ament_copyright/copyright.txt" "--command" "/home/riccardochiaretti/ros2_eloquent/install/ament_copyright/bin/ament_copyright" "--xunit-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/copyright.xunit.xml")
set_tests_properties(copyright PROPERTIES  LABELS "copyright;linter" TIMEOUT "60" WORKING_DIRECTORY "/home/riccardochiaretti/alba_v2_hmi/src/hmi_node")
add_test(cppcheck "/usr/bin/python3" "-u" "/home/riccardochiaretti/ros2_eloquent/install/ament_cmake_test/share/ament_cmake_test/cmake/run_test.py" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/cppcheck.xunit.xml" "--package-name" "hmi_node" "--output-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/ament_cppcheck/cppcheck.txt" "--command" "/home/riccardochiaretti/ros2_eloquent/install/ament_cppcheck/bin/ament_cppcheck" "--xunit-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/cppcheck.xunit.xml")
set_tests_properties(cppcheck PROPERTIES  LABELS "cppcheck;linter" TIMEOUT "120" WORKING_DIRECTORY "/home/riccardochiaretti/alba_v2_hmi/src/hmi_node")
add_test(cpplint "/usr/bin/python3" "-u" "/home/riccardochiaretti/ros2_eloquent/install/ament_cmake_test/share/ament_cmake_test/cmake/run_test.py" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/cpplint.xunit.xml" "--package-name" "hmi_node" "--output-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/ament_cpplint/cpplint.txt" "--command" "/home/riccardochiaretti/ros2_eloquent/install/ament_cpplint/bin/ament_cpplint" "--xunit-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/cpplint.xunit.xml")
set_tests_properties(cpplint PROPERTIES  LABELS "cpplint;linter" TIMEOUT "120" WORKING_DIRECTORY "/home/riccardochiaretti/alba_v2_hmi/src/hmi_node")
add_test(flake8 "/usr/bin/python3" "-u" "/home/riccardochiaretti/ros2_eloquent/install/ament_cmake_test/share/ament_cmake_test/cmake/run_test.py" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/flake8.xunit.xml" "--package-name" "hmi_node" "--output-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/ament_flake8/flake8.txt" "--command" "/home/riccardochiaretti/ros2_eloquent/install/ament_flake8/bin/ament_flake8" "--xunit-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/flake8.xunit.xml")
set_tests_properties(flake8 PROPERTIES  LABELS "flake8;linter" TIMEOUT "60" WORKING_DIRECTORY "/home/riccardochiaretti/alba_v2_hmi/src/hmi_node")
add_test(lint_cmake "/usr/bin/python3" "-u" "/home/riccardochiaretti/ros2_eloquent/install/ament_cmake_test/share/ament_cmake_test/cmake/run_test.py" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/lint_cmake.xunit.xml" "--package-name" "hmi_node" "--output-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/ament_lint_cmake/lint_cmake.txt" "--command" "/home/riccardochiaretti/ros2_eloquent/install/ament_lint_cmake/bin/ament_lint_cmake" "--xunit-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/lint_cmake.xunit.xml")
set_tests_properties(lint_cmake PROPERTIES  LABELS "lint_cmake;linter" TIMEOUT "60" WORKING_DIRECTORY "/home/riccardochiaretti/alba_v2_hmi/src/hmi_node")
add_test(pep257 "/usr/bin/python3" "-u" "/home/riccardochiaretti/ros2_eloquent/install/ament_cmake_test/share/ament_cmake_test/cmake/run_test.py" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/pep257.xunit.xml" "--package-name" "hmi_node" "--output-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/ament_pep257/pep257.txt" "--command" "/home/riccardochiaretti/ros2_eloquent/install/ament_pep257/bin/ament_pep257" "--xunit-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/pep257.xunit.xml")
set_tests_properties(pep257 PROPERTIES  LABELS "pep257;linter" TIMEOUT "60" WORKING_DIRECTORY "/home/riccardochiaretti/alba_v2_hmi/src/hmi_node")
add_test(uncrustify "/usr/bin/python3" "-u" "/home/riccardochiaretti/ros2_eloquent/install/ament_cmake_test/share/ament_cmake_test/cmake/run_test.py" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/uncrustify.xunit.xml" "--package-name" "hmi_node" "--output-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/ament_uncrustify/uncrustify.txt" "--command" "/home/riccardochiaretti/ros2_eloquent/install/ament_uncrustify/bin/ament_uncrustify" "--xunit-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/uncrustify.xunit.xml")
set_tests_properties(uncrustify PROPERTIES  LABELS "uncrustify;linter" TIMEOUT "60" WORKING_DIRECTORY "/home/riccardochiaretti/alba_v2_hmi/src/hmi_node")
add_test(xmllint "/usr/bin/python3" "-u" "/home/riccardochiaretti/ros2_eloquent/install/ament_cmake_test/share/ament_cmake_test/cmake/run_test.py" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/xmllint.xunit.xml" "--package-name" "hmi_node" "--output-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/ament_xmllint/xmllint.txt" "--command" "/home/riccardochiaretti/ros2_eloquent/install/ament_xmllint/bin/ament_xmllint" "--xunit-file" "/home/riccardochiaretti/alba_v2_hmi/src/build-hmi_node-Desktop-Release/test_results/hmi_node/xmllint.xunit.xml")
set_tests_properties(xmllint PROPERTIES  LABELS "xmllint;linter" TIMEOUT "60" WORKING_DIRECTORY "/home/riccardochiaretti/alba_v2_hmi/src/hmi_node")
